### ISSUE TITLE
Linked List 코드 개선

### ISSUE THREAD

**Issue by vntg-ldy** [ldy9037/python-playground#3]
utils/linked_list.py
Python에 Linked List가 없길래 알고리즘 풀이 용으로 구현하였음. 하지만 코드가 너무 지저분 함. 
코드 중복부터 제거 해야겠음.

**Comment by ldy9037** [comment]
가장 반복되는 로직은 검색과 삽입임. 
삽입은 이전, 현재, 다음 노드를 인자로 받아서 연결하는 connectNode 함수로 분리하였음. 이렇게 하면 삽입 뿐만 삭제에서도 쉽게 사용 할 수 있음. 
검색의 경우 index 기준으로 찾는 findNodeByIndex, value 기준으로 찾는 findNodeByValue 함수를 생성하였음. 

위 세 함수를 작성 후 적용하였더니 중복코드가 줄어들고 가독성이 많이 좋아졌음. 

아직 단일 링크로 된 메서드들이 남아있는데 양방향으로 변경하면서 추가적으로 개선해보겠음.

**Comment by ldy9037** [comment]
두 노드 직접 지정해서 서로 연결 시키는 disconnectNode 함수를 추가함.  
기준 노드를 disconnect(기준 노드의 앞뒤 연결)한다고 해서 disconnectNode로 이름을 지었는데 네이밍을 변경해야할듯.

remove, getValue, removeByValue 등 나머지 함수들도 리펙토링 완료함.
이렇게 리펙토링 하고 나서의 장점은 직접 노드를 가져다가 자유롭게 사용할 수 있다는 것임. 특정 알고리즘 문제에서는 이렇게 노드를 직접 가지고 다뤄야 해결할 수 있는 문제들도 있었기 때문에 유용할 듯함. 

일단 동작 테스트 후 티켓닫고 별도의 Repository로 이동시키겠음.

**Comment by ldy9037** [comment]
구현체에 대한 테스트케이스를 작성하였고 테스트 동작 확인하였음. 
일단 emadam-data-structure Repository를 만들었고 해당 코드 이전하였음. 
앞으로 자료구조들은 저 Repo에다가 작성하겠음.

https://github.com/ldy9037/emadam-data-structure
